try
{
    throw new Exception("Divide by 0");
}
catch (DivideByZeroException)
{

}




